# >>> Basic Setup <<<

# Header
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  博客首页: /Home
  作品展示: /works
  留言打卡: /about
  前端导航: /FrontEndGuide
# 静心阅读: /tags
# 光影之路: /instagram
# 随笔: /tags/随笔

# Link to your avatar
avatar: img/head.jpg

# Small icon of Your site
favicon: img/favicon.png

# Social info. Bar
## Keep "mailto:" in Email
## Encrypt email
## RSS requires a plugin to take effect
## https://github.com/hexojs/hexo-generator-feed
subnav:
  mail: "http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=PAkNDgsKBQ4MCnxNTRJfU1E"
  github: "https://github.com/luuman"
  zhihu: "#"
  weibo: "#"
  google: "#"
  twitter: "#"
  linkedin: "#"
  # facebook: "#"
  # rss: /atom.xml
  # pinterest: "#"
  # QQ: "#"
  # wechat: "#"
  # douban: "#"
  # pinboard: "#"
  # stackoverflow: "#"
  # Instagram: "#"
  # segmentfault: "#"

# >>> Conments <<<
# Chose ONE as your comment system and keep others disable.

disqus: 
  #on: true
  shortname: 
  # https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-
  # It is unnecessary to enable disqus here if 
  # you have set "disqus_shortname" in your site's "_config.yml" 

duoshuo: 
  on: true
  domain: 

youyan:
  #on: true
  id: 


# >>> Style Customisation <<<

# Background
## "background_sum": show images form /source/background/
## "on: true": 
## "on: false": background_image: 5
background:
  on: true
  #on: false
  background_sum: 24
  background_image: 109

highlight_style:
  on: true
  inline_code: 5
  code_block: 5
  # Set inline_code to style highlight text
  # Chose a highlight theme for code block
  # inline_code  Value: 0 - 9
  # code_block Value: 0 - 4 

blockquote_style:
  #on: true
  blockquote: 1  # Value: 0 - 7

left_col_width: 300

# Keep TOC title on the same line | 
toc_nowrap: false

# Customize the text on excerpt link
excerpt_link:

# Search Box in left column
# search_box: true

# Animation in Homepage and Loading avatar
animate: true


# >>> Small features | <<<

# Birdhouse button in left column
tagcloud: true

# Blogroll, Link exchange
# friends: false
friends:
  name: http://luuman.github.io/

# reward: true

# 0 1-reward:true 2
reward_type: 2
# wording
reward_wording1: 
reward_wording2: 
# /img/alipay.jpg
alipay: /img/alipay.png

weixin: /img/weixin.png

aboutme:
#aboutme: false

# 是否在新窗口打开链接
# Open ALL link in a new tab
open_in_new: false

# Customize feed link
rss: /atom.xml


# >>> Vendors <<<

# images viewer
## http://www.fancyapps.com/fancybox/
fancybox: true

# Display Math(LaTeX, MathML...)
## https://www.mathjax.org/
mathjax: false

# Socail Share
# share: true
baidushare: true
#showshare: true

# Site Verification for Google and Baidu. HTML label content.
google_site: # pFW527fHrjfI0si2w4NQ0w3cTw12AvvuohAu1PUfqKA
baidu_site: #c167b9feb4f0b208b712c79629c188e4

# Fill in Google Analytics tracking ID, #e.g. UA-XXXXX-X, or Baidu Analytics hash key
google_analytics:
baidu_analytics:

# http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: true
  site_visit:
  page_visit:

TipTitle: true

# Loading
# Loading: true
